apiVersion: v1
kind: Service
metadata:
  name: identity-access-agent
  labels:
    app: identity-access-agent
spec:
  selector:
    app: identity-access-agent
  ports:
    - name: http
      port: 8006
      targetPort: http
      protocol: TCP
    - name: health
      port: 8086
      targetPort: health
      protocol: TCP
    - name: metrics
      port: 9096
      targetPort: metrics
      protocol: TCP
  type: ClusterIP
